version: '3.5'
services:
  app:
    container_name: docker-dbo-test
    image: docker-dbo-test
    ports:
      - "8830:8830"
    depends_on:
      - db
    networks:
      backendme:
        ipv4_address: 172.0.0.1
    command: ifconfig
#    restart: unless-stopped
  db:
    container_name: docker-mysql-2
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=backend_dbo_testing
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - '4306:4306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backendme:
        ipv4_address: 172.0.0.1

volumes:
  db:
    driver: local

networks:
  backendme:
    driver: bridge
    ipam:
      driver: default
      config:
        -  subnet: 172.21.0.0/16