version: '3.5'
services:
  app:
    container_name: docker-dbo-test
    image: docker-dbo-test
    ports:
      - "8830:8830"
    #restart: on-failure
    depends_on:
      - mysql
    networks:
      backendme:
        ipv4_address: 172.21.0.5
  mysql:
    container_name: docker-mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=backend_dbo_testing
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backendme:
        ipv4_address: 172.21.0.3




volumes:
  db:
    driver: local

networks:
  backendme:
    driver: bridge
    ipam:
      driver: default
      config:
        -  subnet: 172.21.0.0/16