version: '3.5'
services:
  app:
    container_name: docker-dbo-test
    image: docker-dbo-test
    ports:
      - "8830:8830"
    #restart: on-failure
    depends_on:
      - db
    networks:
      - fullstack
  db:
    container_name: docker-mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=backend_dbo_testing
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - '3306:3306'
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack


volumes:
  api:
#  database_postgres:                  # Uncomment this when using postgres.
  database_mysql:                   # Uncomment this when using mysql.


networks:
  fullstack:
    driver: bridge